import os
import json
import yaml
from pathlib import Path
from typing import List, Dict, Any
from openpyxl import load_workbook
from agent.config_loader import ConfigLoader
from agent.memory_manager import MemoryManager
from agent.ai_client import AIClient


class GenerateTestsCommand:
    def __init__(self, config: ConfigLoader, memory: MemoryManager, ai_client: AIClient):
        self.config = config
        self.memory = memory
        self.ai = ai_client
        self.output_dir = Path(config.get("output_dir", "framework_output"))
        self.framework_type = config.get_framework_type()
        self.language = config.get("language", "typescript")
        self.test_cases = []
        self.pages_needed = {}

    def execute(self, excel_path: str, force: bool = False) -> bool:
        try:
            excel_file = Path(excel_path)
            if not excel_file.exists():
                print(f"❌ Excel file not found: {excel_path}")
                return False

            print(f"\n[GENERATE] Processing: {excel_path}")
            print(f"Framework: {self.framework_type}\n")

            print("[1/5] Reading test cases from Excel...")
            if not self._read_excel(excel_file):
                return False

            print("[2/5] Grouping test cases by page...")
            self._group_by_page()

            print("[3/5] Generating page objects...")
            self._generate_page_objects(force)

            print("[4/5] Generating test scripts...")
            self._generate_tests()

            print("[5/5] Saving state...")
            self.memory.save()

            self._print_summary()
            return True

        except Exception as e:
            print(f"❌ Generate failed: {e}")
            import traceback
            traceback.print_exc()
            return False

    def _read_excel(self, excel_path: Path) -> bool:
        try:
            wb = load_workbook(excel_path)
            ws = wb.active

            headers = [cell.value for cell in ws[1]]
            print(f"  ✓ Found columns: {headers}")

            test_count = 0
            for row in ws.iter_rows(min_row=2, values_only=False):
                test_case = {}
                for idx, header in enumerate(headers):
                    if header:
                        test_case[header.lower()] = row[idx].value

                if test_case.get("testcaseid"):
                    self.test_cases.append(test_case)
                    test_count += 1

            print(f"  ✓ Read {test_count} test cases")
            return True

        except Exception as e:
            print(f"  ❌ Failed to read Excel: {e}")
            return False

    def _group_by_page(self):
        for tc in self.test_cases:
            page = tc.get("page", "UnknownPage")
            if page not in self.pages_needed:
                self.pages_needed[page] = {"locators": {}, "tests": []}
            self.pages_needed[page]["tests"].append(tc)

        print(f"  ✓ Found {len(self.pages_needed)} unique pages")
        for page in self.pages_needed.keys():
            print(f"    - {page} ({len(self.pages_needed[page]['tests'])} tests)")

    def _generate_page_objects(self, force: bool = False):
        for page_name, page_data in self.pages_needed.items():
            if self.memory.page_exists(page_name) and not force:
                print(f"  ⓘ {page_name} already exists (use --force to regenerate)")
                continue

            page_folder = self.output_dir / "pages" / page_name.lower()
            page_folder.mkdir(parents=True, exist_ok=True)

            locators_file = page_folder / "locators.yaml"
            with open(locators_file, "w") as f:
                f.write(f"# {page_name} Locators - Add locators here\n")
                f.write("# Format:\n")
                f.write("# element_name:\n")
                f.write("#   xpath: //xpath/here\n")
                f.write("#   id: element_id\n")

            if self.language == "python":
                page_file = page_folder / f"{page_name}.py"
                page_content = f'''# Generated by UI Testing Agent - edit freely

class {page_name}:
    """Page object for {page_name}"""

    def __init__(self, driver):
        self.driver = driver
        # Load locators from locators.yaml

    # Add page methods here
    # Example: def click_login_button(self):
'''
            elif self.language == "java":
                page_file = page_folder / f"{page_name}.java"
                page_content = f'''// Generated by UI Testing Agent - edit freely

public class {page_name} {{
    private WebDriver driver;

    public {page_name}(WebDriver driver) {{
        this.driver = driver;
    }}

    // Add page methods here
}}
'''
            elif self.language in ["typescript", "javascript"]:
                page_file = page_folder / f"{page_name}.ts"
                page_content = f'''// Generated by UI Testing Agent - edit freely

export class {page_name} {{
    constructor(private page: Page) {{}}

    // Add page methods here
}}
'''
            else:
                page_file = page_folder / f"{page_name}.py"
                page_content = f'''# Generated by UI Testing Agent - edit freely

class {page_name}:
    """Page object for {page_name}"""

    def __init__(self, driver):
        self.driver = driver
        # Load locators from locators.yaml

    # Add page methods here
    # Example: def click_login_button(self):
'''

            with open(page_file, "w") as f:
                f.write(page_content)

            self.memory.register_page(page_name, str(page_file))
            print(f"  ✓ Created: pages/{page_name.lower()}/{page_file.name}")

    def _generate_tests(self):
        for page_name, page_data in self.pages_needed.items():
            test_count = 0

            for test_case in page_data["tests"]:
                tc_id = test_case.get("testcaseid", "unknown")
                tc_name = test_case.get("testcasename", "unnamed")

                if tc_id in self.memory.memory["test_cases_processed"]:
                    print(f"  ⓘ {tc_id} already processed")
                    continue

                test_folder = self.output_dir / "tests" / page_name.lower()
                test_folder.mkdir(parents=True, exist_ok=True)

                test_filename = f"test_{tc_id.lower()}.py"
                test_file = test_folder / test_filename

                steps = test_case.get("steps", "")
                expected = test_case.get("expectedresult", "")

                test_content = f'''# Generated by UI Testing Agent - edit freely
# Test Case: {tc_id}
# Name: {tc_name}

def test_{tc_id.lower()}():
    """
    {tc_name}

    Steps:
    {steps}

    Expected:
    {expected}
    """
    # TODO: Implement test logic using page objects
    assert True
'''

                with open(test_file, "w") as f:
                    f.write(test_content)

                self.memory.register_test(tc_id, tc_name, str(test_file))
                self.memory.mark_test_processed(tc_id)
                print(f"  ✓ Created: tests/{page_name.lower()}/{test_filename}")
                test_count += 1

            if test_count > 0:
                print(f"  Generated {test_count} tests for {page_name}")

    def _print_summary(self):
        print(f"\n{'='*60}")
        print(f"✅ TEST GENERATION COMPLETE")
        print(f"{'='*60}")
        print(f"\nPages Created: {len(self.pages_needed)}")
        print(f"Tests Created: {len(self.test_cases)}")
        print(f"\nNext Steps:")
        print(f"  1. Add locators to pages/*/locators.yaml")
        print(f"  2. Implement page object methods")
        print(f"  3. Implement test steps in tests/*/test_*.py")
        print(f"  4. Run: python agent/agent.py --action run")
        print(f"\n{'='*60}\n")
